### PR TITLE
[astro] Fix istio sidecar shutdown on newer GKE

### PR DESCRIPTION
**Pull request by jedcunningham**
Newer GKE verions have started to emit multiple running events for a
given pod with the sidecar still being shown as running. We will put
retries around shutting down the sidecar and also check the current
status of the sidecar, not just the status at the time of the event.

e.g: GKE > 1.18.20.901

Related: astronomer/issue#3476

### CODE REVIEW

**Review by kaxil — APPROVED** [review]

**Comment by andriisoldatenko** [comment]
@jedcunningham thanks looks good, is it possible to add a test wdyt?

**Review by andriisoldatenko — APPROVED** [review]

**Comment by kaxil** [comment]
Test is moot on 1.10.x at the very least, since this change is isolated for us, I think we are OK without tests

**Comment by andriisoldatenko** [comment]
do we need similar commit for all airflow versions ?
cc @kaxil

**Comment by kaxil** [comment]
> do we need similar commit for all airflow versions ?
> cc @kaxil

Yup, we will backport it to all

**Pull request merged**
