### PR TITLE
Support Postgres 12.2

### PR DESCRIPTION
**Pull request by kaxil**
resolves https://github.com/astronomer/issues/issues/1028

### CODE REVIEW

**Comment by kaxil** [comment]
@ashb Do we want to support Postgres **9.6** , **10** and **12.2** ?

Should we remove MySql tests from our Travis Build?

**Comment by kaxil** [comment]
I have updated that it https://github.com/astronomer/airflow/pull/474/commits/cf5ecc8715813d94b151af75aea2b0201f155b53 Let me know what you think.

**Comment by ashb** [comment]
I think we might need to support mysql still :(

**Comment by kaxil** [comment]
> I think we might need to support mysql still :(

Updated

**Pull request merged**
