### PR TITLE
Bump to v1.10.7+astro.9

### PR DESCRIPTION
**Pull request by kaxil**
In-line to release ap-airflow 1.10.7-9 docker image

### CODE REVIEW

**Comment by ashb** [comment]
Do we have Changelog here? Or is that in ap-airflow?

**Comment by kaxil** [comment]
> Do we have Changelog here? Or is that in ap-airflow?

Haven't created it yet. But will do it when I create a tag for v1.10.7+astro.9 and add it in ap-airflow too.

**Comment by ashb** [comment]
If the changelog lives in this repo we should create it before changing this version, no?

**Comment by kaxil** [comment]
> If the changelog lives in this repo we should create it before changing this version, no?

No, we don't (or haven't yet updated Changelog in this repo for any versions). We only add changelog in `ap-airflow` repo and when we create tag.

Example: https://github.com/astronomer/airflow/releases/tag/v1.10.10%2Bastro.1
Ap-airflow Example: https://github.com/astronomer/ap-airflow/blob/master/1.10.10/CHANGELOG.md

**Comment by kaxil** [comment]
> Though I wonder why all the tests are failing?

I fixed the static tests and all the tests pass in https://travis-ci.com/github/astronomer/airflow/builds/162321681 except the Cassandra ones

**Pull request merged**
